export const CLASS_REGISTER_REQUEST = "CLASS_REGISTER_REQUEST";
export const CLASS_REGISTER_SUCCESS = "CLASS_REGISTER_SUCCESS";
export const CLASS_REGISTER_FAIL = "CLASS_REGISTER_FAIL";

export const CLASS_LIST_REQUEST = "CLASS_LIST_REQUEST";
export const CLASS_LIST_SUCCESS = "CLASS_LIST_SUCCESS";
export const CLASS_LIST_FAIL = "CLASS_LIST_FAIL";

export const CLASS_DELETE_REQUEST = "CLASS_DELETE_REQUEST";
export const CLASS_DELETE_SUCCESS = "CLASS_DELETE_SUCCESS";
export const CLASS_DELETE_FAIL = "CLASS_DELETE_FAIL";

export const DIVISION_REGISTER_REQUEST = "DIVISION_REGISTER_REQUEST";
export const DIVISION_REGISTER_SUCCESS = "DIVISION_REGISTER_SUCCESS";
export const DIVISION_REGISTER_FAIL = "DIVISION_REGISTER_FAIL";

export const DIVISION_LIST_REQUEST = "DIVISION_LIST_REQUEST";
export const DIVISION_LIST_SUCCESS = "DIVISION_LIST_SUCCESS";
export const DIVISION_LIST_FAIL = "DIVISION_LIST_FAIL";

export const DIVISION_DELETE_REQUEST = "DIVISION_DELETE_REQUEST";
export const DIVISION_DELETE_SUCCESS = "DIVISION_DELETE_SUCCESS";
export const DIVISION_DELETE_FAIL = "DIVISION_DELETE_FAIL";
