export const INFOFORM_REGISTER_REQUEST = "INFOFORM_REGISTER_REQUEST";
export const INFOFORM_REGISTER_SUCCESS = "INFOFORM_REGISTER_SUCCESS";
export const INFOFORM_REGISTER_FAIL = "INFOFORM_REGISTER_FAIL";

export const INFOFORM_LIST_REQUEST = "INFOFORM_LIST_REQUEST";
export const INFOFORM_LIST_SUCCESS = "INFOFORM_LIST_SUCCESS";
export const INFOFORM_LIST_FAIL = "INFOFORM_LIST_FAIL";

export const INFOFORM_DELETE_REQUEST = "INFOFORM_DELETE_REQUEST";
export const INFOFORM_DELETE_SUCCESS = "INFOFORM_DELETE_SUCCESS";
export const INFOFORM_DELETE_FAIL = "INFOFORM_DELETE_FAIL";
