export const SUBJECT_REGISTER_REQUEST = "SUBJECT_REGISTER_REQUEST";
export const SUBJECT_REGISTER_SUCCESS = "SUBJECT_REGISTER_SUCCESS";
export const SUBJECT_REGISTER_FAIL = "SUBJECT_REGISTER_FAIL";

export const SUBJECT_LIST_REQUEST = "SUBJECT_LIST_REQUEST";
export const SUBJECT_LIST_SUCCESS = "SUBJECT_LIST_SUCCESS";
export const SUBJECT_LIST_FAIL = "SUBJECT_LIST_FAIL";

export const SUBJECT_DELETE_REQUEST = "SUBJECT_DELETE_REQUEST";
export const SUBJECT_DELETE_SUCCESS = "SUBJECT_DELETE_SUCCESS";
export const SUBJECT_DELETE_FAIL = "SUBJECT_DELETE_FAIL";
